---
- name: "Playbook - Register Variable"
  hosts: 172.16.10.14
  gather_facts: false

  tasks:
    - name: "NTP Configuration"
      cisco.ios.ios_config:
        src: "ntp.j2"
      notify:
        - NTP_Handler
      register: ntp_output

  handlers:
    - name: NTP_Handler
      ansible.builtin.debug:
        msg: "{{ ntp_output }}"
