---
- name: Load Jinja2 Template
  hosts: 172.16.10.11, 172.16.10.14
  gather_facts: false

  tasks:
    - name: Configure OSPF
      ansible.builtin.template:
        src: "~/ansible-cbt-lab/templates/{{ device_vendor }}.j2"
        dest: "./ospf_config_{{ inventory_hostname }}.conf"
        mode: '0644'
