---
- name: "Playbook - Register Variable"
  hosts: 172.16.10.14
  gather_facts: false

  tasks:
    - name: "NTP Configuration"
      cisco.ios.ios_config:
        src: "ntp.j2"
      register: ntp_output

    - name: "Print NTP Result"
      ansible.builtin.debug:
        msg: "{{ ntp_output }}"
