version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
sphinx:
  configuration: docs/source/conf.py

python:
  # Install python package before building the docs
  install:
    - requirements: requirements.txt

formats:
  - pdf
  - epub
